name: Build gl4es-114
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build GL4ES
        run: |
         wget https://dl.google.com/android/repository/android-ndk-r25c-linux.zip
         unzip android-ndk-r25c-linux.zip >> /dev/null
         ./android-ndk-r25c/ndk-build APP_BUILD_SCRIPT=./Android.mk NDK_PROJECT_PATH=.
         ./android-ndk-r25c/ndk-build APP_BUILD_SCRIPT=./Android_debug.mk NDK_PROJECT_PATH=.
      - name: Upload GL4ES libs
        uses: actions/upload-artifact@v2
        with:
          name: gl4es-114
          path: libs/*
      - name: Upload GL4ES debug libs
        uses: actions/upload-artifact@v2
        with:
          name: gl4es-114
          path: 'obj/**/*.so'
        
